{% set name = "hole-filling-liepa" %}
{% set version = "0.0.3" %}

package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
#  path: .
  url: https://github.com/russelmann/hole-filling-liepa/archive/v{{ version }}.tar.gz

build:
  number: 0
  
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - cmake
    - ninja
    - pybind11
    - eigen
  host:
    - python
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - hole_filling_liepa

about:
  home: https://github.com/russelmann/hole-filling-liepa
  license: MIT
  license_family: MIT
  summary: Hole filling algorithm by P. Liepa.
