{% set name = "hole-filling-liepa" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
#git_rev: v0.0.1
#git_url: https://github.com/russelmann/hole-filling-liepa.git
  path: .

build:
  number: 0
  preserve_egg_dir: True
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --use-feature=in-tree-build"
  
requirements:
  build:
    - cmake
  host:
    - python
  run:
    - python
    - numpy

#test:
#  imports:
#    - hole-filling-liepa

about:
  home: https://github.com/russelmann/hole-filling-liepa
  license: MIT
  license_family: MIT
  summary: Hole filling algorithm by P. Liepa.
